/**
 * Flashcards.
 *
 *   GET  /api/flashcards/[docId]                  → all sessions
 *   POST /api/flashcards/[docId] { action:"generate", topic? }
 *                                                 → new session with cards
 *   POST /api/flashcards/[docId] { action:"rate", sessionId, cardIndex, rating, userAnswer? }
 *                                                 → record per-card rating
 *   POST /api/flashcards/[docId] { action:"end", sessionId }
 *                                                 → mark session ended; trigger KG eval
 *   DELETE /api/flashcards/[docId]?sessionId=...
 *
 * The deck is generated by codex from the document text + (if available)
 * the knowledge graph so cards target real concepts. Ratings follow the
 * 1=again / 2=hard / 3=good / 4=easy convention from FSRS.
 */

import { NextResponse } from "next/server";
import { runJson, toCodexErrorPayload } from "@/lib/ai";
import { getDoc } from "@/lib/store";
import {
  loadWorkContext,
  saveWorkContext,
  newId,
  type Flashcard,
  type FlashcardSession,
} from "@/lib/work-context";
import {
  flashcardsGenerateSchema,
  type FlashcardsGenerateResult,
} from "@/lib/schemas-kg";
import { loadKG } from "@/lib/kg";
import { scheduleEvaluation } from "@/lib/kg-runner";

export const runtime = "nodejs";
export const maxDuration = 180;

const SYSTEM = `You are Get It.'s flashcard generator.

Goal: produce a focused deck (4–10 cards) for the requested topic that
forces ACTIVE recall and discriminates strong understanding from
memorisation.

CARD QUALITY
  • Atomic: ONE fact / mechanism per card.
  • Question first, then a tight answer (1–3 sentences max). No multiple-
    choice, no "list all". Force the student to produce the answer.
  • Mix tiers: ~30% definitions / vocabulary, ~40% mechanism / why-does-
    this-happen, ~30% applied (small problems, edge cases).
  • Avoid trick questions; avoid yes/no questions; avoid cards solved by
    pattern-matching surface words.
  • If the source is in Italian / Spanish / etc., write the cards in that
    language.

OUTPUT
A JSON object matching the schema. No prose.`;

function generationPrompt(docId: string, topic: string): string {
  const doc = getDoc(docId)!;
  const kg = loadKG(docId);
  const kgPart =
    kg && kg.status === "ready"
      ? `\nKEY CONCEPTS:\n${kg.nodes.map((n) => `- ${n.label}: ${n.summary}`).join("\n")}\n`
      : "";
  // Full document text — no excerpt cap (upload bounds size at MAX_PDF_PAGES).
  // Stable blocks first (instructions, document, concepts), the variable TOPIC
  // last so repeated generations on the same doc share a cacheable prefix.
  const fullText = doc.extracted.pages
    .map((p) => `[page ${p.pageIndex + 1}]\n${p.text}`)
    .join("\n\n");
  return `${SYSTEM}

DOCUMENT: ${doc.filename}
${kgPart}
DOCUMENT TEXT:
${fullText}

TOPIC: ${topic === "all" ? "the whole document — broad coverage" : topic}

Produce the deck now. Output JSON.`;
}

export async function GET(
  _req: Request,
  ctx: { params: Promise<{ docId: string }> },
) {
  const { docId } = await ctx.params;
  if (!getDoc(docId)) {
    return NextResponse.json({ error: "doc not found" }, { status: 404 });
  }
  const wc = loadWorkContext(docId);
  return NextResponse.json({ sessions: wc.flashcards });
}

type Body =
  | { action: "generate"; topic?: string }
  | { action: "rate"; sessionId: string; cardIndex: number; rating: 1 | 2 | 3 | 4; userAnswer?: string }
  | { action: "end"; sessionId: string };

export async function POST(
  req: Request,
  ctx: { params: Promise<{ docId: string }> },
) {
  const { docId } = await ctx.params;
  if (!getDoc(docId)) {
    return NextResponse.json({ error: "doc not found" }, { status: 404 });
  }
  const body = (await req.json()) as Body;
  const wc = loadWorkContext(docId);

  if (body.action === "generate") {
    const topic = (body.topic ?? "all").trim() || "all";
    let data: FlashcardsGenerateResult;
    try {
      ({ data } = await runJson<FlashcardsGenerateResult>(
        generationPrompt(docId, topic),
        flashcardsGenerateSchema,
        { reasoning: "low" },
      ));
    } catch (e) {
      const p = toCodexErrorPayload(e);
      return NextResponse.json({ error: p.message, kind: p.kind }, { status: 503 });
    }
    const session: FlashcardSession = {
      id: newId(),
      topic,
      createdAt: Date.now(),
      cards: data.cards.map((c) => ({ q: c.q, a: c.a })),
    };
    const reloaded = loadWorkContext(docId);
    reloaded.flashcards.unshift(session);
    saveWorkContext(reloaded);
    return NextResponse.json({ session });
  }

  if (body.action === "rate") {
    const session = wc.flashcards.find((s) => s.id === body.sessionId);
    if (!session) return NextResponse.json({ error: "session not found" }, { status: 404 });
    const card: Flashcard | undefined = session.cards[body.cardIndex];
    if (!card) return NextResponse.json({ error: "card index out of range" }, { status: 400 });
    if (body.rating < 1 || body.rating > 4) {
      return NextResponse.json({ error: "rating must be 1..4" }, { status: 400 });
    }
    card.rating = body.rating;
    if (body.userAnswer != null) card.userAnswer = body.userAnswer.slice(0, 1000);
    card.answeredAt = Date.now();
    saveWorkContext(wc);
    return NextResponse.json({ session });
  }

  if (body.action === "end") {
    const session = wc.flashcards.find((s) => s.id === body.sessionId);
    if (!session) return NextResponse.json({ error: "session not found" }, { status: 404 });
    if (!session.endedAt) {
      session.endedAt = Date.now();
      saveWorkContext(wc);
      scheduleEvaluation(docId);
    }
    return NextResponse.json({ session });
  }

  return NextResponse.json({ error: "unknown action" }, { status: 400 });
}

export async function DELETE(
  req: Request,
  ctx: { params: Promise<{ docId: string }> },
) {
  const { docId } = await ctx.params;
  if (!getDoc(docId)) {
    return NextResponse.json({ error: "doc not found" }, { status: 404 });
  }
  const url = new URL(req.url);
  const sessionId = url.searchParams.get("sessionId");
  if (!sessionId) return NextResponse.json({ error: "sessionId required" }, { status: 400 });
  const wc = loadWorkContext(docId);
  wc.flashcards = wc.flashcards.filter((s) => s.id !== sessionId);
  saveWorkContext(wc);
  return NextResponse.json({ ok: true });
}
